# .github/workflows/mirror-gitee.yml
name: Sync To Gitee
on:
  push:
    branches: [ main, master ] #需要同步的分支
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ github.repository_owner }}
          dst: gitee/${{ secrets.GITEE_USER }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: ${{ github.event.repository.name }}
          ignore-empty-workdir: true   # 屏蔽 Empty workdir 警告